# density_profile_gui_ui.tcl --
#
# UI generated by GUI Builder Build 146 on 2012-12-18 18:22:52 from:
#    /home/toni/compile/vmd-utils/vmd_density_profile/density_profile_gui.ui
# THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
# The associated callback file should be modified instead.
#

# Declare the namespace for this dialog
namespace eval density_profile_gui {}

package require Tk
# density_profile_gui::ui --
#
#   Create the UI for this dialog.
#
# ARGS:
#   root     the parent window for this form
#   args     a catch-all for other args, but none are expected
#
proc density_profile_gui::ui {root args} {
    # this handles '.' as a special case
    set base [expr {($root == ".") ? "" : $root}]
    variable ROOT $root
    variable BASE $base
    variable SCRIPTDIR ; # defined in main script


    # Widget Initialization
    variable _frame_1 [frame $BASE._frame_1]
    variable frame_Zsource [frame $BASE.frame_Zsource]
    variable _frame_3 [frame $BASE._frame_3]
    variable _frame_4 [frame $BASE._frame_4]
    variable _frame_5 [frame $BASE._frame_5]
    variable _label_1 [label $BASE._label_1 \
	    -font {helvetica 10} \
	    -text "Atom selection"]
    variable _label_2 [label $BASE._label_2 \
	    -font {helvetica 10} \
	    -text "Projection axis"]
    variable _label_3 [label $BASE._label_3 \
	    -font {helvetica 10} \
	    -text "Resolution (\u00C5)"]
    variable _label_5 [label $BASE._label_5 \
	    -font {helvetica 10} \
	    -justify "right" \
	    -text "Guess atomic number Z\nfrom attribute"]
    variable _entry_1 [entry $BASE._entry_1 \
	    -font {helvetica 10} \
	    -invalidcommand [namespace code [list _entry_1_invalidcommand]] \
	    -justify "center" \
	    -textvariable "density_profile::dp_args(selection)" \
	    -validatecommand [namespace code [list _entry_1_validatecommand]] \
	    -xscrollcommand [namespace code [list _entry_1_xscrollcommand]]]
    variable _label_6 [label $BASE._label_6 \
	    -font {helvetica 10 bold} \
	    -text "VMD Density Profile Tool"]
    variable _radiobutton_2 [radiobutton $BASE._radiobutton_2 \
	    -command [namespace code [list _radiobutton_2_command]] \
	    -font {helvetica 10} \
	    -text "x" \
	    -value "x" \
	    -variable "density_profile::dp_args(axis)"]
    variable _radiobutton_3 [radiobutton $BASE._radiobutton_3 \
	    -command [namespace code [list _radiobutton_3_command]] \
	    -font {helvetica 10} \
	    -text "y" \
	    -value "y" \
	    -variable "density_profile::dp_args(axis)"]
    variable _radiobutton_4 [radiobutton $BASE._radiobutton_4 \
	    -command [namespace code [list _radiobutton_4_command]] \
	    -font {helvetica 10} \
	    -text "z" \
	    -value "z" \
	    -variable "density_profile::dp_args(axis)"]
    variable _entry_2 [entry $BASE._entry_2 \
	    -invalidcommand [namespace code [list _entry_2_invalidcommand]] \
	    -justify "center" \
	    -textvariable "density_profile::dp_args(resolution)" \
	    -validatecommand [namespace code [list _entry_2_validatecommand]] \
	    -width 8 \
	    -xscrollcommand [namespace code [list _entry_2_xscrollcommand]]]
    variable radiobutton_Zsource_name [radiobutton $BASE.radiobutton_Zsource_name \
	    -command [namespace code [list radiobutton_Zsource_name_command]] \
	    -font {helvetica 10} \
	    -state "disabled" \
	    -text "name" \
	    -value "name" \
	    -variable "density_profile::dp_args(Zsource)"]
    variable radiobutton_Zsource_type [radiobutton $BASE.radiobutton_Zsource_type \
	    -command [namespace code [list radiobutton_Zsource_type_command]] \
	    -font {helvetica 10} \
	    -state "disabled" \
	    -text "type" \
	    -value "type" \
	    -variable "density_profile::dp_args(Zsource)"]
    variable radiobutton_Zsource_element [radiobutton $BASE.radiobutton_Zsource_element \
	    -command [namespace code [list radiobutton_Zsource_element_command]] \
	    -font {helvetica 10} \
	    -state "disabled" \
	    -text "element" \
	    -value "element" \
	    -variable "density_profile::dp_args(Zsource)"]
    variable _label_7 [label $BASE._label_7 \
	    -font {helvetica 10} \
	    -text "Density profile of"]
    variable radiobutton_mass [radiobutton $BASE.radiobutton_mass \
	    -command [namespace code [list radiobutton_mass_command]] \
	    -font {helvetica 10} \
	    -text "mass" \
	    -value "mass" \
	    -variable "density_profile::dp_args(rho)"]
    variable radiobutton_charge [radiobutton $BASE.radiobutton_charge \
	    -command [namespace code [list radiobutton_charge_command]] \
	    -font {helvetica 10} \
	    -text "charge" \
	    -value "charge" \
	    -variable "density_profile::dp_args(rho)"]
    variable radiobutton_electrons [radiobutton $BASE.radiobutton_electrons \
	    -command [namespace code [list radiobutton_electrons_command]] \
	    -font {helvetica 10} \
	    -text "electrons" \
	    -value "electrons" \
	    -variable "density_profile::dp_args(rho)"]
    variable plot [button $BASE.plot \
	    -command [namespace code [list plot_command]] \
	    -font {helvetica 10 bold} \
	    -text "Plot"]
    variable close [button $BASE.close \
	    -command [namespace code [list close_command]] \
	    -font {helvetica 10 bold} \
	    -text "Close"]
    variable radiobutton_atoms [radiobutton $BASE.radiobutton_atoms \
	    -command [namespace code [list radiobutton_atoms_command]] \
	    -font {helvetica 10} \
	    -text "number" \
	    -value "number" \
	    -variable "density_profile::dp_args(rho)"]
    variable checkbox_Zsource_partial [checkbutton $BASE.checkbox_Zsource_partial \
	    -command [namespace code [list checkbox_Zsource_partial_command]] \
	    -font {helvetica 10} \
	    -state "disabled" \
	    -text "Consider partial charges" \
	    -variable "density_profile::dp_args(partial_charges)"]
    variable _label_4 [label $BASE._label_4 \
	    -font {helvetica 10} \
	    -pady 6 \
	    -text "Computes 1-D projections of various atomic densities. The computation is performed in a single frame, a trajectory, or averaged over multiple frames." \
	    -wraplength 400]
    variable _label_8 [label $BASE._label_8 \
	    -font {helvetica 10} \
	    -text "Frames from"]
    variable _label_9 [label $BASE._label_9 \
	    -font {helvetica 10} \
	    -text "First"]
    variable _entry_3 [entry $BASE._entry_3 \
	    -invalidcommand [namespace code [list _entry_3_invalidcommand]] \
	    -justify "center" \
	    -textvariable "density_profile::dp_args(frame_from)" \
	    -validatecommand [namespace code [list _entry_3_validatecommand]] \
	    -width 8 \
	    -xscrollcommand [namespace code [list _entry_3_xscrollcommand]]]
    variable _label_10 [label $BASE._label_10 \
	    -font {helvetica 10} \
	    -text " to"]
    variable _checkbutton_2 [checkbutton $BASE._checkbutton_2 \
	    -command [namespace code [list _checkbutton_2_command]] \
	    -font {helvetica 10} \
	    -text "Average" \
	    -variable "density_profile::dp_args(average)"]
    variable _entry_4 [entry $BASE._entry_4 \
	    -invalidcommand [namespace code [list _entry_4_invalidcommand]] \
	    -justify "center" \
	    -textvariable "density_profile::dp_args(frame_to)" \
	    -validatecommand [namespace code [list _entry_4_validatecommand]] \
	    -width 8 \
	    -xscrollcommand [namespace code [list _entry_4_xscrollcommand]]]
    variable _label_11 [label $BASE._label_11 \
	    -font {helvetica 10} \
	    -text " step"]
    variable _entry_5 [entry $BASE._entry_5 \
	    -invalidcommand [namespace code [list _entry_5_invalidcommand]] \
	    -justify "center" \
	    -textvariable "density_profile::dp_args(frame_step)" \
	    -validatecommand [namespace code [list _entry_5_validatecommand]] \
	    -width 8 \
	    -xscrollcommand [namespace code [list _entry_5_xscrollcommand]]]
    variable _label_12 [label $BASE._label_12 \
	    -font {helvetica 10} \
	    -pady 6 \
	    -text "See console for information and data files"]
    variable help [button $BASE.help \
	    -bitmap "questhead" \
	    -command [namespace code [list help_command]] \
	    -font {helvetica 10 bold} \
	    -text "?"]
    variable radiobutton_Zsource_mass [radiobutton $BASE.radiobutton_Zsource_mass \
	    -command [namespace code [list radiobutton_Zsource_mass_command]] \
	    -font {helvetica 10} \
	    -state "disabled" \
	    -text "mass" \
	    -value "mass" \
	    -variable "density_profile::dp_args(Zsource)"]
    variable menu [menu $BASE.menu]
    variable menuitem1 [menu $BASE.menuitem1 \
	    -tearoff 0]
    $BASE.menu add cascade \
	    -label "Help" \
	    -menu $BASE.menuitem1
    $BASE.menuitem1 add command \
	    -command "density_profile_gui::help_docs" \
	    -label "Documentation..."
    $BASE.menuitem1 add command \
	    -command "density_profile_gui::help_about" \
	    -label "About..."


    # Geometry Management

    grid $BASE._frame_1 -in $root -row 5 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "w"
    grid $BASE.frame_Zsource -in $root -row 6 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "w"
    grid $BASE._frame_3 -in $root -row 3 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "w"
    grid $BASE._frame_4 -in $root -row 9 -column 1 \
	    -columnspan 2 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "news"
    grid $BASE._frame_5 -in $root -row 7 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "ew"
    grid $BASE._label_1 -in $root -row 4 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "e"
    grid $BASE._label_2 -in $root -row 5 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "e"
    grid $BASE._label_3 -in $base._frame_1 -row 1 -column 4 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "e"
    grid $BASE._label_5 -in $root -row 6 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "e"
    grid $BASE._entry_1 -in $root -row 4 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "ew"
    grid $BASE._label_6 -in $root -row 1 -column 1 \
	    -columnspan 2 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "s"
    grid $BASE._radiobutton_2 -in $base._frame_1 -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "ew"
    grid $BASE._radiobutton_3 -in $base._frame_1 -row 1 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "ew"
    grid $BASE._radiobutton_4 -in $base._frame_1 -row 1 -column 3 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "ew"
    grid $BASE._entry_2 -in $base._frame_1 -row 1 -column 5 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "ew"
    grid $BASE.radiobutton_Zsource_name -in $base.frame_Zsource -row 1 -column 3 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE.radiobutton_Zsource_type -in $base.frame_Zsource -row 1 -column 4 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE.radiobutton_Zsource_element -in $base.frame_Zsource -row 1 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE._label_7 -in $root -row 3 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "e"
    grid $BASE.radiobutton_mass -in $base._frame_3 -row 1 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE.radiobutton_charge -in $base._frame_3 -row 1 -column 3 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE.radiobutton_electrons -in $base._frame_3 -row 1 -column 4 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE.plot -in $base._frame_4 -row 1 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "nsew"
    grid $BASE.close -in $base._frame_4 -row 1 -column 3 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "nsew"
    grid $BASE.radiobutton_atoms -in $base._frame_3 -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE.checkbox_Zsource_partial -in $base.frame_Zsource -row 1 -column 5 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "w"
    grid $BASE._label_4 -in $root -row 2 -column 1 \
	    -columnspan 2 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "nsew"
    grid $BASE._label_8 -in $root -row 7 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "e"
    grid $BASE._label_9 -in $base._frame_5 -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE._entry_3 -in $base._frame_5 -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "ew"
    grid $BASE._label_10 -in $base._frame_5 -row 1 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "e"
    grid $BASE._checkbutton_2 -in $base._frame_5 -row 1 -column 6 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "e"
    grid $BASE._entry_4 -in $base._frame_5 -row 1 -column 3 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "ew"
    grid $BASE._label_11 -in $base._frame_5 -row 1 -column 4 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "e"
    grid $BASE._entry_5 -in $base._frame_5 -row 1 -column 5 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "ew"
    grid $BASE._label_12 -in $root -row 8 -column 1 \
	    -columnspan 2 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE.help -in $base._frame_4 -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "nsew"
    grid $BASE.radiobutton_Zsource_mass -in $base.frame_Zsource -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""

    # Resize Behavior
    grid rowconfigure $root 1 -weight 0 -minsize 17 -pad 0
    grid rowconfigure $root 2 -weight 1 -minsize 44 -pad 0
    grid rowconfigure $root 3 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $root 4 -weight 0 -minsize 38 -pad 0
    grid rowconfigure $root 5 -weight 0 -minsize 48 -pad 0
    grid rowconfigure $root 6 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $root 7 -weight 0 -minsize 45 -pad 0
    grid rowconfigure $root 8 -weight 0 -minsize 2 -pad 0
    grid rowconfigure $root 9 -weight 0 -minsize 27 -pad 0
    grid columnconfigure $root 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 2 -weight 1 -minsize 119 -pad 0
    grid rowconfigure $base._frame_1 1 -weight 0 -minsize 7 -pad 0
    grid columnconfigure $base._frame_1 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._frame_1 2 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._frame_1 3 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._frame_1 4 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._frame_1 5 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $base.frame_Zsource 1 -weight 0 -minsize 16 -pad 0
    grid columnconfigure $base.frame_Zsource 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base.frame_Zsource 2 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base.frame_Zsource 3 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base.frame_Zsource 4 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base.frame_Zsource 5 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $base._frame_3 1 -weight 0 -minsize 15 -pad 0
    grid columnconfigure $base._frame_3 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._frame_3 2 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._frame_3 3 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._frame_3 4 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $base._frame_4 1 -weight 0 -minsize 10 -pad 0
    grid columnconfigure $base._frame_4 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._frame_4 2 -weight 1 -minsize 40 -pad 0
    grid columnconfigure $base._frame_4 3 -weight 1 -minsize 40 -pad 0
    grid rowconfigure $base._frame_5 1 -weight 0 -minsize 2 -pad 0
    grid columnconfigure $base._frame_5 1 -weight 1 -minsize 40 -pad 0
    grid columnconfigure $base._frame_5 2 -weight 0 -minsize 24 -pad 0
    grid columnconfigure $base._frame_5 3 -weight 1 -minsize 40 -pad 0
    grid columnconfigure $base._frame_5 4 -weight 0 -minsize 27 -pad 0
    grid columnconfigure $base._frame_5 5 -weight 1 -minsize 40 -pad 0
    grid columnconfigure $base._frame_5 6 -weight 0 -minsize 78 -pad 0
    $ROOT configure -menu $BASE.menu
}
