# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded density_profile 1.1 [list source [file join $dir density_profile.tcl]]
package ifneeded density_profile_gui 1.1 [list source [file join $dir density_profile_gui.tcl]]


# May throw error if not under gui, or already registered. They must be ignored.
catch {	package require density_profile_gui; menu tk register density_profile_gui density_profile_gui::density_profile_tk "Analysis/Density Profile Tool" } msg

